---
- name: es 6.6.0
  hosts: esnodes
  roles:
    - role: elastic.elasticsearch
      become: yes
  vars:
    es_instance_name: "es-node-1"
    es_config:
      cluster.name: "test-cluster"
      node.name: "es-node-1"
      network.host: "0.0.0.0"
      node.master: true
      xpack.security.authc.realms.file1.order: 0
      xpack.security.authc.realms.file1.type: file
      xpack.security.authc.realms.native1.order: 1
      xpack.security.authc.realms.native1.type: native
    es_heap_size: 4g
    es_enable_xpack: true
    es_api_basic_auth_username: elastic
    es_api_basic_auth_password: xA123456
    es_xpack_features:
      - security
      - alerting
    es_message_auth_file: system_key
    es_role_mapping:
      power_user:
        - "cn=admins,dc=example,dc=com"
      user:
        - "cn=users,dc=example,dc=com"
        - "cn=admins,dc=example,dc=com"
    es_users:
      native:
        kibana4_server:
          password: xA123456 
          roles:
            - kibana4_server
        logstash_system:
          #this should be successfully modified
          password: xA123456 
          #this will be ignored
          roles:
            - kibana4_server
        elastic:
          password: xA123456 
      file:
        es_admin:
          password: xA123456 
          roles:
            - admin
        testUser:
          password: xA123456 
          roles:
            - power_user
            - user
    es_roles:
      file:
        admin:
          cluster:
            - all
          indices:
            - names: '*'
              privileges:
                - all
        power_user:
          cluster:
            - monitor
          indices:
            - names: '*'
              privileges:
                - all
        user:
          indices:
            - names: '*'
              privileges:
                - read
        kibana4_server:
          cluster:
              - monitor
          indices:
            - names: '.kibana'
              privileges:
                - all
      native:
        logstash:
          cluster:
            - manage_index_templates
          indices:
            - names: 'logstash-*'
              privileges:
                - write
                - delete
                - create_index
